### ISSUE TITLE
javasrc2cpg: problem with type resolving

### ISSUE THREAD

**Issue by fabsx00** [joernio/joern#1137]
When running `javasrc2cpg` on the source code of HelloShiftLeft, I noticed that for the class `InvalidCustomerRequest`, two type declarations are generated:

```
joern> cpg.typeDecl.name("InvalidCustomerRequest.*").l 
res6: List[TypeDecl] = List(
  TypeDecl(
    id -> 1987L,
    aliasTypeFullName -> None,
    astParentFullName -> "io.shiftleft.exception",
    astParentType -> "NAMESPACE_BLOCK",
    code -> "InvalidCustomerRequestException",
    columnNumber -> None,
    filename -> "/home/fabs/Downloads/HelloShiftLeft/src/main/java/io/shiftleft/exception/InvalidCustomerRequestException.java",
    fullName -> "io.shiftleft.exception.InvalidCustomerRequestException",
    inheritsFromTypeFullName -> ArraySeq("java.lang.RuntimeException"),
    isExternal -> false,
    lineNumber -> None,
    name -> "InvalidCustomerRequestException",
    order -> 1
  ),
  TypeDecl(
    id -> 3421L,
    aliasTypeFullName -> None,
    astParentFullName -> "<global>",
    astParentType -> "NAMESPACE_BLOCK",
    code -> "<empty>",
    columnNumber -> None,
    filename -> "<unknown>",
    fullName -> "<unresolved>.InvalidCustomerRequestException",
    inheritsFromTypeFullName -> ArraySeq(),
    isExternal -> true,
    lineNumber -> None,
    name -> "InvalidCustomerRequestException",
    order -> -1
  )
)
```

The class is available in the source code, so, it seems to me that the second (external) class should not be present. My guess is that it was generated because `InvalidCustomerRequest` is used, but where it is used, we were unable to resolve it.

**Comment by johannescoetzee** [comment]
The issue mentioned in the description was fixed by https://github.com/joernio/joern/pull/1155. It turns out the JavaParserTypeSolver needs to be pointed at the true sources root to work, so in this case `InvalidCustomerRequestException` could not be resolved since `javasrc2cpg` was not invoked with the specific argument `.../HelloShiftLeft/src/main/java`.

Closing this in favour of https://github.com/joernio/joern/issues/1169 which I'll be using to track general type resolution fixes and improvements for now.
