### ISSUE TITLE
javasrc2cpg: children of calls to NEW operator missing

### ISSUE THREAD

**Issue by fabsx00** [joernio/joern#1171]
For the statement

```
authToken = new AuthToken(AuthToken.ADMIN);
```
we end up with an AST that consists of three nodes:
- a call to <operator>.assignment
- the identifier `authToken`
- a call to `operator.alloc`

We are however, missing the AST for the argument `AuthToken.ADMIN` and the call to `<init>`.

**Comment by johannescoetzee** [comment]
This is an unfortunate implementation detail that's a result of compatibility with `java2cpg`. The statement
```
authToken = new AuthToken(AuthToken.ADMIN);
```
is represented as 
```
authToken = <operator>.alloc();
authToken.<init>(AuthToken.ADMIN);
```
to mimic how this is represented in byte code. Because of this, a query like 
```
cpg.method.internal.name("doPostLogin").call.code("authToken =.*").ast.l
```
will only return the subtree for the `alloc` call, as the `init` call is completely separate from the assignment.

Instead, the query
```
cpg.method.name("doPostLogin").call.code("new AuthToken.*").l 
```
can be used to find both the `alloc` and `init` calls.
