### ISSUE TITLE
importCode throwing NoClassDefFoundError

### ISSUE THREAD

**Issue by vishesh27k** [joernio/joern#1429]
Joern importCode getting stuck for a specific repository.
Repo link: https://github.com/paypal/PayPal-Java-SDK

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/45128646/170183005-3f563fa5-f185-43cd-85fd-0b328c223219.png">

**Comment by ojaswa1942** [comment]
cc @tuxology

**Comment by mpollmeier** [comment]
Thanks for reporting! 

The root cause is that we marked 'gradle-tooling-api' as a non-transitive dependency in x2cpg. 

There are a few alternatives to fixing this, e.g. make it an explicit dependency of javasrc (https://github.com/joernio/joern/pull/1430) or make it a regular dependency in x2cpg (https://github.com/joernio/joern/pull/1431).

**Comment by mpollmeier** [comment]
I just remembered: we made it a non-transitive dependency because it's not on maven central and is only relevant for a few frontends. Let's go with #1430 then.
