### ISSUE TITLE
where is the folder of joernIndex

### ISSUE THREAD

**Issue by longswordinhand** [joernio/joern#1880]
I install joern by following the step in "Quick Installation". After I run the joern, I can not find the folder of joernIndex. Your helps are appreciated.

**Comment by itsacoderepo** [comment]
Hello longswordinhand,

you are probably expecting the outcome of an old version of joern, while using the latest version. 

Unfortunately, your text is not giving any hints about what you want to achieve, so that i cannot give you any advise but just to read the documentation: https://docs.joern.io/home.

**Comment by longswordinhand** [comment]
Could you please which version can output the joernIndex files?
Thanks.
