### ISSUE TITLE
Wrong with modifierType

### ISSUE THREAD

**Issue by INT2ECALL** [joernio/joern#2041]
I found that the modifierType of method is wrong When I try to analyze [commons-collections-3.2.1](https://repo1.maven.org/maven2/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1-sources.jar)

The modifierType of method LazyMap is protected, but joern print public : 

![image](https://user-images.githubusercontent.com/91420400/204705421-a7ede62c-27ee-45d8-962c-0a51e693c453.png)

![image](https://user-images.githubusercontent.com/91420400/204704593-d7060eec-b36a-400f-8b56-bcac64f44b80.png)

Is there any way to fix this problem?

**Comment by johannescoetzee** [comment]
It looks like there are a couple of things going on here. 

The first is that the method names I'm getting with the latest version of joern do not match the result of your query. For consistency with the closed source java bytecode frontend, constructor names are all set to `<init>`, so for example the full names I get for the constructors for this typeDecl are:
```
joern> cpg.typeDecl.name(".*LazyMap.*").method.fullName.l 
res1: List[String] = List(
  "org.apache.commons.collections.map.LazyMap.<init>:void(java.util.Map,org.apache.commons.collections.Factory)",
  "org.apache.commons.collections.map.LazyMap.<init>:void(java.util.Map,org.apache.commons.collections.Transformer)",
  ... and the other methods
)
```
Are you perhaps using an older version of the javasrc frontend? 

The query in question is also not getting the modifiers for the `LazyMap` method, but is rather getting the modifiers for the typeDecl containing the constructors (due to the `.typeDecl` call). The output in this case is correct, since this class does have a `public` modifier.

The constructor methods themselves have no modifiers though, so this is definitely still a bug:
```

joern> cpg.typeDecl.name(".*LazyMap.*").method.nameExact("<init>").modifier.l 
res4: List[Modifier] = List()
```

**Comment by johannescoetzee** [comment]
Closing this since the constructor methods are now created with the correct modifiers:

```
joern> cpg.typeDecl.name(".*LazyMap.*").method.nameExact("<init>").modifier.modifierType.l 
res3: List[String] = List("CONSTRUCTOR", "PROTECTED", "CONSTRUCTOR", "PROTECTED")
```
