### ISSUE TITLE
Unit tests in jssrc2cpg are taking more time than usual

### ISSUE THREAD

**Issue by Liyw979** [joernio/joern#2179]
- in ```1.1.1382```: it takes 52 seconds to run test ```in io.joern.jssrc2cpg```
- in ```1.1.1384```: it takes 1min 56 seconds

**Comment by mpollmeier** [comment]
https://github.com/joernio/joern/pull/2180

**Comment by mpollmeier** [comment]
cc @max-leuthaeuser

**Comment by max-leuthaeuser** [comment]
This is due to https://github.com/joernio/joern/pull/2172
We query the results of the Typescript compiler / type checker to add more type information.
Its only activated for https://github.com/joernio/joern/blob/master/joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/types/TSTypesTest.scala

**Comment by Liyw979** [comment]
I get this. It's good to have type infos.
