### ISSUE TITLE
Scripts are not included in distribution

### ISSUE THREAD

**Issue by fabsx00** [joernio/joern#243]
The releases created by `sbt createDistribution` do not contain the scripts in `joern-cli/src/main/resources/scripts`

**Comment by johannescoetzee** [comment]
I tested this with Joern release 1.1.307. The scripts are now included in the distribution at
```
❯ find . -regex ".*.sc"
./joern-cli/scripts/c/const-ish.sc
./joern-cli/scripts/c/malloc-leak.sc
./joern-cli/scripts/c/malloc-overflow.sc
./joern-cli/scripts/c/pointer-to-int.sc
./joern-cli/scripts/c/syscalls.sc
./joern-cli/scripts/c/userspace-memory-access.sc
./joern-cli/scripts/general/list-funcs.sc
./joern-cli/scripts/binary/mips-gadgets.sc
```

This isn't at the path mentioned in the original issue, but it seems reasonable to assume that the script path has changed in the 18 months since this issue was created, so I'm closing this issue :) Please re-open it if the path is incorrect.
