### ISSUE TITLE
How can I set a custom property to a node and query with this property

### ISSUE THREAD

**Issue by Liyw979** [joernio/joern#2729]
**Describe the solution you'd like**
I want to do `dstGraph.setNodeProperty(method, "modified", true)` in a custom pass, 
and later do `cpg.method.property("modified").l`

**Comment by mpollmeier** [comment]
That should "just work", there's a lot of passes in the joern codebase that do exactly that. If you need more help debugging something, please share a complete example. 

Some notes
1) don't forget to apply the pass!
2) 'modified' isn't a legal property on `method`, since it's not defined in the [schema](https://github.com/ShiftLeftSecurity/codepropertygraph/tree/master/schema/src/main/scala/io/shiftleft/codepropertygraph/schema).

**Comment by maltek** [comment]
if you want to set properties not defined in the schema, you could also consider using tags (which are implemented not as properties but as separate nodes connected via edges):

```
joern> val m = cpg.method.head
m: Method = Method(
    ...
)

joern> m.start.newTagNodePair("modified", "true").store()


joern> run.commit
The graph has been modified. You may want to use the `save` command to persist changes to disk.  All changes will also be saved collectively on exit
res4: Cpg = Cpg (Graph [18 nodes])

joern> cpg.tag.nameExact("modified").valueExact("true").method.l
res5: List[Method] = List(
  Method(
    ...
  )
)
```

**Comment by Liyw979** [comment]
Thanks! `newTagNodePair` and `newTagNode` are the way to go for custom properties.
reference: https://docs.joern.io/cpgql/augmentation-directives/
