### ISSUE TITLE
[Bug] Legacy csharp2cpg compatibility problem

### ISSUE THREAD

**Issue by yzn12345** [joernio/joern#2809]
**Describe the bug**
Using https://github.com/AppThreat to generate cpg for c# code, importing into joern. Expecting fieldAccess node exists. But its type is set unknown so I guess it's compatibility problem

**Expected behavior**
fieldAccess node should exist

**Screenshots**
![image](https://github.com/joernio/joern/assets/56081290/23ac763b-f74a-4e6e-a82f-684cc5c194e9)
![image](https://github.com/joernio/joern/assets/56081290/e1246f3c-c65e-4710-ab37-12a4339f1e0e)

**Desktop (please complete the following information):**
 - OS
 - Joern Version 
 - Java version

**Comment by mpollmeier** [comment]
which frontend did you use, or rather how did you generate the cpg?

**Comment by yzn12345** [comment]
> which frontend did you use, or rather how did you generate the cpg?
https://github.com/AppThreat/cpggen
frontend: csharp2cpg-v1.0.1454-net-win-x64.zip

**Comment by yzn12345** [comment]
> Check if your code contains the JavaScript files js files. That might have triggered JS frontend and generated the CPG.

All other node types work fine. Except that empty result set returned for query: cpg.fieldAccess which is abnormal.

Will investigate further tomorrow and get u updated.

**Comment by mpollmeier** [comment]
Ok... this was why I asked about the frontend.
csharp2cpg is a Qwiet/Shiftleft proprietary frontend for paid customers only. 

I'm surprised that cpggen includes it in it's distribution, and would say that's the real issue here. Yes, anyone can download it from our CDN, but the cpgs have no use in joern: they use a different schema and they only work with additional code that's proprietary again. 

The paid-for brother of joern that can work with csharp2cpg is called `ocular`. If you're interested in that please let us know and we can put you in touch with the sales reps at Qwiet (formerly Shiftleft).

**Comment by prabhu** [comment]
@yzn12345 I'm author of cpggen and a former consultant of Qwiet.AI. There were miscommunications and to cut long story short CPG binary frontends from Qwiet.AI were removed from cpggen with version 1.5.0 and unlikely to return back.

I will let you know the moment an oss implementation becomes available.

Thank you for using cpggen and apologies for any inconvenience caused.
