### ISSUE TITLE
Struct assignments missing

### ISSUE THREAD

**Issue by m1cm1c** [joernio/joern#405]
When loading the following code into Joern, there graph is incomplete:

```
struct foobar {
  int    foo;
  int    bar;
};

int main(int argc, char *argv[]) {
  struct foobar foobarInstance = { .bar = 27, .foo = 23 };
  return 1;
}
```

`foobar` does occur. But neither `foobarInstance` nor the assignments involving numbers `27` and `23` do occur.

**Comment by m1cm1c** [comment]
I discovered that this leads to an empty block for some reason. This block is connected via an incoming AST edge but does not have any outgoing edges at all.

**Comment by johannescoetzee** [comment]
This issue seems to be fixed when using the new Eclipse CDT-based frontend (which is now the default C/C++ frontend in Joern). The intializer is represented by an `<operator>.arrayInitializer` call which is a bit of a misnomer, but structurally everything seems to be there. 

![image](https://user-images.githubusercontent.com/25384566/141277150-06a56db8-d44a-4988-b4f2-75dccb54d8ec.png)
