### ISSUE TITLE
[ruby] Chained Calls

### ISSUE THREAD

**Issue by DavidBakerEffendi** [joernio/joern#4396]
The grammar seems to not handle chains calls in certain expressions (or at all). E.g.
```ruby
class User < ApplicationRecord

  def self.authenticate(email, password)
    auth = nil
    user = find_by_email(email)
    raise "#{email} doesn't exist!" if !(user)
    if user.password == Digest::MD5.hexdigest(password)
      auth = user
    else
      raise "Incorrect Password!"
    end
    return auth
  end

end
```

The code `Digest::MD5.hexdigest(password)` is only picked up as a `Digest.MD5` member access, and `hexdigest` onwards is discarded within the context of the equality expression.

**Comment by DavidBakerEffendi** [comment]
What is also likely, is that we simply need a visitor under `CommandCommandOrPrimaryValueContext` or `PrimaryValuePrimaryContext`

**Comment by xavierpinho** [comment]
Precedences in Ruby can be very tricky, so please don't take my word on this without proper testing, but - for what is worth - raising the precedence of `primaryValue` in `commandOrPrimaryValue` seems to fix this without breaking any tests. Diff:

```diff
Index: joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4 b/joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4
--- a/joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4	(revision 34a15dec8ff2ef4efe65a290f815e19def665368)
+++ b/joern-cli/frontends/rubysrc2cpg/src/main/antlr4/io/joern/rubysrc2cpg/parser/RubyParser.g4	(date 1711461215438)
@@ -408,14 +408,14 @@
     ;
 
 commandOrPrimaryValue
-    :   command
+    :   primaryValue
+        # primaryValueCommandOrPrimaryValue
+    |   command
         # commandCommandOrPrimaryValue
     |   NOT commandOrPrimaryValue
         # notCommandOrPrimaryValue
     |   commandOrPrimaryValue (AND|OR) NL* commandOrPrimaryValue
         # keywordAndOrCommandOrPrimaryValue
-    |   primaryValue
-        # primaryValueCommandOrPrimaryValue
     ;
 
 block

```

**Comment by AndreiDreyer** [comment]
Seems neither a visitor or the suggested parser changes will work. The parser change ended up causing a lot of warnings to be thrown on the Railsgoat repo, and the visitor addition doesn't capture the entire context required. It seems that the `EqualityExpression` is where the problem lies, as that only captures the `user.password == Digest::MD5`, and the rest is then discarded. I tried adding a `visitMemberAccessCommand` which manages to grab the whole line, but the `ctx.primary()` for this is the `user.password == Digest::MD5`, so similar issues were run into here.

Going to investigate different changes to the parser to see if I can't get this to work properly
