### ISSUE TITLE
[ruby] HereDoc in Function Argument

### ISSUE THREAD

**Issue by DavidBakerEffendi** [joernio/joern#4600]
HereDoc in a function argument is interesting, as in this case, the heredoc only starts from the next line onwards, and is meant to be inserted in the argument index where the first heredoc token starts.

```ruby
def foo(arg)
  bar(arg, <<-SOME_HEREDOC, arg + 1)
   inside here doc
  SOME_HEREDOC
end
```

Right now, the above causes a syntax issue which will fail parsing for that file.

**Comment by xavierpinho** [comment]
At one point I had something barely working using the following approach:
* Run the lexer, having a distinguished token for `<<-` (and its variants). Token-wise, `SOME_HEREDOC` would be some kind of identifier.
* Before we run the parser, go through the token stream (we can make it a list) and rearrange sequences of `<<-` `IDENTIFIER` ... `\n` ... `IDENTIFIER` (matching the first one) into another synthetic token representing the heredoc's text.

The thing is this isn't the whole story, though: they could be nested, interpolated, have methods directly applied to them, etc and it's all these use-cases that make this more time-consuming than it should otherwise be. I still reckon that the sanest way to go about this is to have a 2nd lexer pass though, hence why I'm sharing this somewhat positive experiment here.
