### ISSUE TITLE
Why Joern downloading binary from privado repository?

### ISSUE THREAD

**Issue by rohitcoder** [joernio/joern#4931]
Joern is an Apache 2.0 licensed project and is advertised as a fully independent tool. However, I noticed that it downloads a binary to generate ASTs for Golang, which raises some concerns. Wouldn't it be better to maintain a copy of this binary directly within the Joern organization instead of relying on an external repo? This approach would eliminate the dependency on downloading and running a binary from another source. Additionally, I couldn't find a license attached to the Privado repository, which could pose legal and compliance issues in the future. What are your thoughts on this?

https://github.com/joernio/joern/blob/3440c26a9de390645c6415d322af8b08c074895b/joern-cli/frontends/gosrc2cpg/build.sbt#L39-L41

**Comment by DavidBakerEffendi** [comment]
Hi @rohitcoder, this is a valid concern. Initially, Privado was tightly coupled to Joern and they infact developed the golang frontend, and funded a lot of development into the Python, JavaScript, Java, Ruby (1st iteration) frontends, and also started the development of the C# frontend. 

However, since they have moved towards an internal fork, it would be good, especially for future maintainability, to have a `joernio` version. This binary downloading occurs for other frontends such as C# and JavaScript, and is mostly done if the best parser available is the native one (and it's usually in the language itself).

**Comment by AndreiDreyer** [comment]
Resolved by #4989
